### ISSUE TITLE
Why doesn't the index.md not behave same as other pages for sidebars?

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#2]
@philipbaileynar I suspect that the reason is simply how Matt coded up the JS for these? But 
- [ ] why won't the [`index.md`](http://restoration-usu.github.io/WATS-5340-5350/) place its home page (or at least the `title: index title`)? I think this makes it a little confusing when browsing the site if you want to go to the home page. Users either have to browse back to their home page or click the header. Why not make it easy and add at the top of the list the home page using the title label as a name?
- [ ] why doesn't a **Page Contents** show up on the `index.md` page when headers  are used in the document? Is this some assumption that an index page shouldn't have any headers?

**Comment by philipbaileynar** [comment]
I just pushed the change to make the page contents box appear on the home page.

Still noodling on the parent/child page relationship...

**Comment by philipbaileynar** [comment]
parent child is now part of the new theme:

http://riverscapes.northarrowresearch.com/Technical_Reference/jekyll_toolbox.html#parentchild-page-relationships
