### ISSUE TITLE
Attempted to update theme

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#3]
Hey @philipbaileynar ,
I attempted to update the theme with following the instructions on https://github.com/Restoration-USU/WATS-5340-5350/commit/02268165e643dc1ab0d895d99942b823faecf4df following https://github.com/Riverscapes/TemplateDocs. Some things worked, but Its not bringing in the footer (I made some changes to that too), or updating the sidebar navigation like I expected....

Thoughts?

**Comment by joewheaton** [comment]
I reverted the changes as things were breaking left and right... I think I'll need to do a GoTo with this.

**Comment by philipbaileynar** [comment]
I've implemented the TemplateDocs theme from scratch. I don't know the exact source of the problems, but glaring errors in the front-matter like commit e4992f30b92aa4bc60e9be94fc995ea8c17cefb7 were not helping.

I am now fixing my documentation on how to [apply the TemplateDocs theme](http://riverscapes.northarrowresearch.com/Technical_Reference/applying_theme.html) to include the instructions to update the `_config.yml` file.

**Comment by joewheaton** [comment]
Thanks Philip. Makes sense.
