### ISSUE TITLE
Applying Riverscapes Theme

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#5]
Hey @philipbaileynar . How hard would it be to apply the Riverscapes theme to this website? I think I can probably fake it and remember how, but I'm mindful I could screw it up and it takes 15 minutes to help me fix what would have taken you 5 minutes to do in the first place.

**Comment by philipbaileynar** [comment]
Yep, leave it with me.

**Comment by philipbaileynar** [comment]
Done!
