### ISSUE TITLE
Proofread and make edits to new syllabus

### ISSUE THREAD

**Issue by joewheaton** [Restoration-USU/WATS-5340-5350#9]
@mikeclawson I did add a new syllabus page and schedule here: http://capstone.restoration.usu.edu/Syllabus/2022_Spring.html

I did this to be consistent with the other classes as well as get the schedule dialed in a little more. Please proof read for typos or things that don't make sense.

**Comment by mikeclawson** [comment]
Well the picture you found of me isn't the best, but everything else looks correct.

**Comment by joewheaton** [comment]
> Well the picture you found of me isn't the best, but everything else looks correct.

Feel free to replace.... It was what I could find of you in action!
